services:
  # Base de donn√©es MongoDB
  db:
    image: mongo:6.0
    container_name: supfile-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - supfile-network

  # Serveur API Node.js/Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: supfile-backend
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      SERVER_PORT: 5000
      SERVER_HOST: 0.0.0.0
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      UPLOAD_DIR: /usr/src/app/uploads
      CORS_ORIGIN: ${CORS_ORIGIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost:3000/auth/callback/google}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
      GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI:-http://localhost:3000/auth/callback/github}
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/usr/src/app/uploads
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - supfile-network
    restart: unless-stopped

  # Client Web React
  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile.dev
    container_name: supfile-frontend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      VITE_GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-web/src:/app/src
      - /app/node_modules
    networks:
      - supfile-network
    restart: unless-stopped
    depends_on:
      - backend

  # Client Mobile (Flutter)
  mobile:
    build:
      context: ./mobile-app
      dockerfile: Dockerfile
    container_name: supfile-mobile
    environment:
      API_URL: ${VITE_API_URL:-http://localhost:5000}
    ports:
      - "8080:8080"
    volumes:
      - ./mobile-app/lib:/app/lib
    networks:
      - supfile-network
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  backend_data:
    driver: local

networks:
  supfile-network:
    driver: bridge
